services:
  postgres:
    image: postgres:latest
    container_name: postgres
    env_file:
      - .env
    ports:
      - '5432:5432'
    volumes:
      - postgres_data:/var/lib/postgresql/data
    networks:
      - backend

  redis:
    image: redis:latest
    container_name: redis
    ports:
      - '6379:6379'
    networks:
      - backend

  pgadmin:
    image: dpage/pgadmin4:latest
    container_name: pgadmin
    env_file:
      - .env
    ports:
      - '8081:80'
    networks:
      - backend
  minio:
    image: minio/minio:latest
    volumes:
      - ./data:/data
    ports:
      - 9000:9000
      - 9001:9001
    env_file:
      - .env
    networks:
      - backend
    command:  server --console-address ":9001" /data

networks:
  backend:
    driver: bridge

volumes:
  postgres_data:
